// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdT_KKQ83vON4DcZ7txuaECcNoxxxoTdE',
    appId: '1:679424077834:web:d8015b03960e1f16006ff3',
    messagingSenderId: '679424077834',
    projectId: 'kemudi-1db2a',
    authDomain: 'kemudi-1db2a.firebaseapp.com',
    databaseURL: 'https://kemudi-1db2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kemudi-1db2a.appspot.com',
    measurementId: 'G-D4X87MLH9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFzONY8B545i83aWVNDzYQZCIxchSo6_8',
    appId: '1:679424077834:android:a19191ccf9f51882006ff3',
    messagingSenderId: '679424077834',
    projectId: 'kemudi-1db2a',
    databaseURL: 'https://kemudi-1db2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kemudi-1db2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGlz7TqooRcOBMuqroCFfNBKhKycjbBtc',
    appId: '1:679424077834:ios:e73f91db03ea23ab006ff3',
    messagingSenderId: '679424077834',
    projectId: 'kemudi-1db2a',
    databaseURL: 'https://kemudi-1db2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kemudi-1db2a.appspot.com',
    androidClientId: '679424077834-ms9knt0ftl4fbh962f3t1q43uhb90idh.apps.googleusercontent.com',
    iosClientId: '679424077834-e70qsgd6iapi4a7e7pt53uupuldurg2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGlz7TqooRcOBMuqroCFfNBKhKycjbBtc',
    appId: '1:679424077834:ios:e73f91db03ea23ab006ff3',
    messagingSenderId: '679424077834',
    projectId: 'kemudi-1db2a',
    databaseURL: 'https://kemudi-1db2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kemudi-1db2a.appspot.com',
    androidClientId: '679424077834-ms9knt0ftl4fbh962f3t1q43uhb90idh.apps.googleusercontent.com',
    iosClientId: '679424077834-e70qsgd6iapi4a7e7pt53uupuldurg2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegist',
  );
}
